# Generated by Django 2.2.5 on 2019-09-18 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TweeterModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('limit', models.IntegerField(default=10000)),
                ('epochs', models.IntegerField(default=50)),
                ('embedding_dimensions', models.IntegerField(default=25)),
                ('exclude_replies', models.BooleanField(default=True)),
                ('pre_trained_embedding', models.BooleanField(default=False)),
                ('status', models.CharField(default='pending', max_length=30)),
                ('raw_file', models.CharField(max_length=512)),
                ('tweets_file', models.CharField(max_length=512)),
                ('model_file', models.CharField(max_length=512)),
                ('tokenizer_file', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='', max_length=280)),
                ('status', models.CharField(default='pending', max_length=30)),
                ('tweeter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nlptwitter.TweeterModel')),
            ],
        ),
    ]
