# Generated by Django 2.2.5 on 2019-09-15 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nlptwitter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweeter',
            name='status',
            field=models.CharField(default='pending', max_length=30),
        ),
    ]
