# Generated by Django 2.2.5 on 2019-09-15 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nlptwitter', '0002_tweeter_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweeter',
            name='limit',
            field=models.IntegerField(default=10000),
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=280)),
                ('status', models.CharField(default='pending', max_length=30)),
                ('tweeter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nlptwitter.Tweeter')),
            ],
        ),
    ]
