# Generated by Django 2.2.5 on 2019-09-15 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nlptwitter', '0003_auto_20190915_0533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='text',
            field=models.CharField(default='', max_length=280),
        ),
    ]
